# EarlyBird Collective Component

# Headers
coll_earlybird_la_ompi_headers = coll_earlybird.h

# Sources
coll_earlybird_la_sources =     coll_earlybird_component.c     coll_earlybird_module.c     coll_earlybird_allgather.c

# Libraries
coll_earlybird_la_libadd =     

# Include directories
coll_earlybird_la_cppflags =     -I$(top_srcdir)/ompi/ompi/mca/coll/earlybird

# Create the library
lib_LTLIBRARIES = coll_earlybird_la

# Installation
coll_earlybird_la_la_libs = 
